BACKGROUND_IMAGE = 'assets/images/bg3.jpg'
EYE_ICON = 'assets/icons/eye.png'
HOME_ICON = 'assets/icons/home.png'
CREATE_SHEET_ICON ='assets/icons/file-plus.png'
IMPORT_WORKBOOK_ICON = 'assets/icons/arrow-down-circle.png'
ENTER_ATTENDENCE_ICON = 'assets/icons/edit.png'
DOWNLOAD_EXCEL_ICON = 'assets/icons/file-text.png'
CREATE_ADMIN_ICON = 'assets/icons/user-plus.png'
CREATE_USER_ICON = 'assets/icons/users.png'
CHANGE_PASSWORD_ICON = 'assets/icons/change.webp'
DELETE_ICON = 'assets/icons/delete.png'
LOG_OUT_ICON ='assets/icons/log-out.png'
RIGHT_POINTER_ICON = 'assets/icons/right.png'
OPEN_FILE_ICON = 'assets/icons/green.png'
CLOASE_ICON = 'assets/icons/x red.png'

